# Site settings
baseurl = "http://camflow.org/"
languageCode = "en-us"
title = "CamFlow: Practical Whole-System Provenance for Linux"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = "UA-83032453-1"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "CamFlow"
  description = "Practical Whole-System Provenance for Linux"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "tfjmp2@cam.ac.uk"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # hero Section
  [params.hero]
    type = "hero"
    title = "CamFlow"
    description = "Practical Whole-System Provenance for Linux"
		buttontext = "Learn More"
    # the picture is storead at static/images/
    picture = "pic01.jpg"

  # about section
  [[params.block]]
    id = "about"
    type = "text"
    title = "What is CamFlow?"
    description = "CamFlow stands for Cambridge information Flow architecture, the Cam is also the river that flows through Cambridge, UK.\
		CamFlow is a Linux Security Modules (LSMs) designed to capture data provenance for the purpose of system audit.\
		The provenance capture mechanism is highly configurable, and can fit the needs of many different type of applications.\
		CamFlow can stack with existing security modules such as SELinux.\
		Visit our project on <a href=\"https://github.com/CamFlow\" target=\"_blank\">github</a>."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic02.jpg"

  # skill section
  [[params.block]]
    id = "research"
    type = "text"
    title = "Research Project"
    description = "CamFlow development started in 2014 as the result of research at the University of Cambridge <a href=\"https://www.cl.cam.ac.uk/research/srg/opera/\" target=\"_blank\">Opera Research Group</a> \
		(grant <a href=\"http://gow.epsrc.ac.uk/NGBOViewGrant.aspx?GrantRef=EP/K011510/1\" target=\"_blank\">EPSRC EP/K011510/1</a>). \
		Further development has been supported by Harvard University's <a href=\"https://crcs.seas.harvard.edu/\" target=\"_blank\">Center for Research on Computation and Society</a> as part of the <a href=\"https://projects.iq.harvard.edu/provenance-at-harvard\" target=\"_blank\">Provenance@Harvard</a> project \
		(NSF grant <a href=\"https://nsf.gov/awardsearch/showAward?AWD_ID=1450277\" target=\"_blank\">SSI-1450277</a>) \
		and the University of Cambridge's <a href=\"https://www.cl.cam.ac.uk/research/dtg/www/\" target=\"_blank\">Digital Technology Group</a>.\
		<table>\
      <tr>\
        <td><a href=\"https://www.cl.cam.ac.uk/research/srg/opera/\" target=\"_blank\"><img src=\"./images/cambridge.png\" width=\"80%\"></a></td>\
        <td><a href=\"https://syrah.eecs.harvard.edu/\" target=\"_blank\"><img src=\"./images/harvard.png\" width=\"80%\"></a></td>\
      </tr>\
    </table>"
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic03.jpg"

	# skill section
  [[params.block]]
    id = "installation"
    type = "text"
    title = "Installation"
    description = "For instructions on how to install and use CamFlow see our <a href=\"https://github.com/CamFlow/documentation/blob/master/README.md\" target=\"_blank\">documentation</a>.\
		We also provide <a href=\"https://github.com/CamFlow/vagrant\" target=\"_blank\">vagrant scripts</a> to easily setup virtual machines running CamFlow.\
		The source code of every CamFlow components is available on <a href=\"https://github.com/CamFlow/\" target=\"_blank\">github</a>.\
		Please do not hesitate to fork our project or create issues to report bugs."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic04.jpg"

	# skill section
  [[params.block]]
    id = "contributing"
    type = "text"
    title = "Contributing"
    description = "The easiest way to contribute to CamFlow is by submitting issues to suggest improvement or report bug.\
		When reporting a bug, please specify the version of CamFlow you are running and your Linux distribution.\
		To contribute a new feature, please fork the repository of the component you wish to improve, and submit a pull request against the dev branch.\
		The pull request must pass the continuous integration test before it can be merged."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic05.jpg"

	# skill section
  [[params.block]]
    id = "publications"
    type = "text"
    title = "Publications"
    description = "CamFlow is discussed in the following publications. \
		Details given in these papers may be outdated - please refer to the code if in doubt or contact us. \
		<br><br>\
		Pasquier T., Han X., Goldstein M., Moyer T., Eyers D., Seltzer M. and J. Bacon <strong>Practical Whole-System Provenance Capture</strong>. Symposium on Cloud Computing (SoCC'17) (2017), ACM. <a href=\"https://github.com/CamFlow/publications/raw/master/2017socc.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2017socc.bib\" target=\"_blank\">bib</a> <a href=\"https://github.com/CamFlow/publications/raw/master/2017socc-poster.pdf\" target=\"_blank\">poster</a><br>\
		Pasquier T., Singh J., , Bacon J., and Eyers D. <strong>Information Flow Audit for PaaS Clouds</strong>. In International Conference on Cloud Engineering (IC2E) (2016), IEEE. <a href=\"https://github.com/CamFlow/publications/raw/master/2016ic2e.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2016ic2e.bib\" target=\"_blank\">bib</a><br>\
		Pasquier T., Singh J., Eyers D., and Bacon J. <strong>CamFlow: Managed Data-Sharing for Cloud Services</strong>. IEEE Transactions on Cloud Computing (2015), IEEE. <a href=\"https://github.com/CamFlow/publications/raw/master/2015camflowtcc.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2015camflowtcc.bib\" target=\"_blank\">.bib</a>"
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "pic04.jpg"

  # infos section
  [[params.block]]
    id = "others"
    type = "text"
    title = "CamFlow use cases"
    description = "Han X., Pasquier T. and Seltzer M. <strong>Provenance-based Intrusion Detection: Opportunities and Challenges</strong>. Workshop on the Theory and Practice of Provenance (TaPP'18) (2018), USENIX. <a href=\"https://github.com/CamFlow/publications/raw/master/2018tapp.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2018tapp.bib\" target=\"_blank\">bib</a> <a href=\"https://www.usenix.org/conference/tapp2018/presentation/han\" target=\"_blank\">website</a><br>\
		Wang F., Joung Y., and Mickens J. <strong>Cobweb: Practical Remote Attestation Using Contextual Graphs</strong>. Workshop on System Software for Trusted Execution (SysTEX'17) (2017), ACM. <a href=\"https://mickens.seas.harvard.edu/files/mickens/files/cobweb.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://dl.acm.org/downformats.cfm?id=3152705&parent_id=3152701&expformat=bibtex&CFID=837880949&CFTOKEN=91832166\" target=\"_blank\">.bib</a><br>\
		Han X., Pasquier T., Ranjan T., Goldstein M., and Seltzer M. <strong>FRAPpuccino: Fault-detection through Runtime Analysis of Provenance</strong>. Workshop on Hot Topics in Cloud Computing (HotCloud'17) (2017), USENIX. <a href=\"https://github.com/CamFlow/publications/raw/master/2017hotcloud.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2017hotcloud.bib\" target=\"_blank\">bib</a> <a href=\"https://www.usenix.org/conference/hotcloud17/program/presentation/han\" target=\"_blank\">website</a> <a href=\"https://github.com/CamFlow/publications/raw/master/2017hotcloud-poster.pdf\" target=\"_blank\">poster</a><br>\
		Pasquier T.  and Eyers D. <strong>Information Flow Audit for Transparency and Compliance in the Handling of Personal Data</strong>. IC2E International Workshop on Legal and Technical Issues in Cloud Computing (CLaw'16) (2016),  IEEE. <a href=\"https://github.com/CamFlow/publications/raw/master/2016claw.pdf\" target=\"_blank\">.pdf</a> <a href=\"https://raw.githubusercontent.com/CamFlow/publications/master/2016claw.bib\" target=\"_blank\">bib</a><br>\
		"
    # the picture is storead at static/images/
    picture = "pic03.jpg"

#  # custom section
#  [[params.block]]
#    id = "important"
#    # to make custom section copy <theme>/layouts/partials/text.html to /layouts/partials/custom.html and edit it according to your needs.
#    type = "custom"
#    title = "Don't forget"
#    description = "Curabitur massa ante, semper at massa et, semper pellentesque velit. Duis tempor est nisi, a gravida risus malesuada eget. Nunc rutrum arcu laoreet mauris sodales vehicula. Nunc iaculis felis ac dui egestas, vel ullamcorper tellus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lacinia sem porttitor, fringilla metus at, convallis quam. Integer convallis a justo non pellentesque."
#    # the picture is storead at static/images/
#    picture = "pic04.jpg"

  # contact form
  [[params.block]]
    id = "contact"
    type = "contact"
    title = "Get in Touch"
    picture = "pic02.jpg"

    [params.block.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

  # footer section
  # this section includes last block and social icons

  [params.footer]
    enable = true

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/tfjmp"

      [[params.footer.social]]
        title = "e-mail"
        icon = "fa-envelope"
        link = "mailto:tfjmp2@cam.ac.uk"

      [[params.footer.social]]
        title = "github"
        icon = "fa-github"
        link = "https://github.com/camflow"

      [[params.footer.social]]
        title = "slack"
        icon = "fa-slack"
        link = "https://camflow.slack.com"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "Â© <a href=\"http://tfjmp.org/\" target=\"_blank\">Thomas Pasquier</a>, University of Cambridge"
